
const dataSource = [
  { key: '1', name: 'Olivia', age: 32, address: 'New York Park' },
  { key: '2', name: 'Ethan', age: 40, address: 'London Park' },
  { key: '3', name: 'Emma', age: 50, address: 'London Park' },
  { key: '4', name: 'Olivia', age: 44, address: 'Paris Street' },
  { key: '5', name: 'Lucas', age: 55, address: 'Paris Street' },
  { key: '6', name: 'Ethan', age: 23, address: 'Berlin Avenue' },
  { key: '7', name: 'Isabella', age: 43, address: 'Sydney Harbor' },
  { key: '8', name: 'Mason', age: 39, address: 'Berlin Avenue' },
  { key: '9', name: 'Olivia', age: 24, address: 'Sydney Harbor' },
  { key: '10', name: 'Emma', age: 26, address: 'Paris Street' },
  { key: '11', name: 'Ethan', age: 27, address: 'Berlin Avenue' },
  { key: '12', name: 'Mason', age: 60, address: 'Sydney Harbor' },
  { key: '13', name: 'Olivia', age: 39, address: 'London Park' },
  { key: '14', name: 'Emma', age: 23, address: 'New York Park' },
  { key: '15', name: 'Lucas', age: 46, address: 'Berlin Avenue' },
  { key: '16', name: 'Ava', age: 27, address: 'Berlin Avenue' },
  { key: '17', name: 'Sophia', age: 55, address: 'Berlin Avenue' },
  { key: '18', name: 'Lucas', age: 41, address: 'Paris Street' },
  { key: '19', name: 'Ethan', age: 20, address: 'Sydney Harbor' },
  { key: '20', name: 'Ethan', age: 32, address: 'London Park' },
  { key: '21', name: 'Liam', age: 30, address: 'London Park' },
  { key: '22', name: 'Olivia', age: 30, address: 'Paris Street' },
  { key: '23', name: 'Liam', age: 49, address: 'Paris Street' },
  { key: '24', name: 'Isabella', age: 41, address: 'London Park' },
  { key: '25', name: 'Mason', age: 56, address: 'London Park' },
  { key: '26', name: 'Noah', age: 25, address: 'New York Park' },
  { key: '27', name: 'Noah', age: 42, address: 'Paris Street' },
  { key: '28', name: 'Liam', age: 32, address: 'Paris Street' },
  { key: '29', name: 'Noah', age: 24, address: 'London Park' },
  { key: '30', name: 'Emma', age: 40, address: 'Sydney Harbor' },
  { key: '31', name: 'Mason', age: 40, address: 'Berlin Avenue' },
  { key: '32', name: 'Isabella', age: 23, address: 'New York Park' },
  { key: '33', name: 'Ava', age: 43, address: 'New York Park' },
  { key: '34', name: 'Mason', age: 42, address: 'Paris Street' },
  { key: '35', name: 'Noah', age: 60, address: 'Sydney Harbor' },
  { key: '36', name: 'Lucas', age: 30, address: 'London Park' },
  { key: '37', name: 'Mason', age: 32, address: 'London Park' },
  { key: '38', name: 'Ava', age: 24, address: 'London Park' },
  { key: '39', name: 'Lucas', age: 35, address: 'New York Park' },
  { key: '40', name: 'Lucas', age: 37, address: 'Berlin Avenue' },
  { key: '41', name: 'Ava', age: 60, address: 'New York Park' },
  { key: '42', name: 'Ava', age: 28, address: 'Paris Street' },
  { key: '43', name: 'Isabella', age: 31, address: 'New York Park' },
  { key: '44', name: 'Lucas', age: 60, address: 'New York Park' },
  { key: '45', name: 'Noah', age: 26, address: 'Paris Street' },
  { key: '46', name: 'Emma', age: 28, address: 'Sydney Harbor' },
  { key: '47', name: 'Olivia', age: 33, address: 'Berlin Avenue' },
  { key: '48', name: 'Ava', age: 52, address: 'London Park' },
  { key: '49', name: 'Mason', age: 41, address: 'Paris Street' },
  { key: '50', name: 'Noah', age: 40, address: 'Berlin Avenue' },
  { key: '51', name: 'Liam', age: 28, address: 'Sydney Harbor' },
  { key: '52', name: 'Emma', age: 52, address: 'Sydney Harbor' },
];

export default dataSource;
  